// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	context "context"

	cart "github.com/pangolin-do-golang/tech-challenge-cart-api/internal/core/cart"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// IService is an autogenerated mock type for the IService type
type IService struct {
	mock.Mock
}

// AddProduct provides a mock function with given fields: ctx, clientID, product
func (_m *IService) AddProduct(ctx context.Context, clientID uuid.UUID, product *cart.Product) error {
	ret := _m.Called(ctx, clientID, product)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *cart.Product) error); ok {
		r0 = rf(ctx, clientID, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Cleanup provides a mock function with given fields: clientID
func (_m *IService) Cleanup(clientID uuid.UUID) error {
	ret := _m.Called(clientID)

	var r0 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = rf(clientID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EditProduct provides a mock function with given fields: ctx, clientID, product
func (_m *IService) EditProduct(ctx context.Context, clientID uuid.UUID, product *cart.Product) error {
	ret := _m.Called(ctx, clientID, product)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *cart.Product) error); ok {
		r0 = rf(ctx, clientID, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetFullCart provides a mock function with given fields: clientID
func (_m *IService) GetFullCart(clientID uuid.UUID) (*cart.Cart, error) {
	ret := _m.Called(clientID)

	var r0 *cart.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*cart.Cart, error)); ok {
		return rf(clientID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *cart.Cart); ok {
		r0 = rf(clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cart.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadCart provides a mock function with given fields: ctx, clientID
func (_m *IService) LoadCart(clientID uuid.UUID) (*cart.Cart, error) {
	ret := _m.Called(clientID)

	var r0 *cart.Cart
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (*cart.Cart, error)); ok {
		return rf(clientID)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) *cart.Cart); ok {
		r0 = rf(clientID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*cart.Cart)
		}
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(clientID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveProduct provides a mock function with given fields: ctx, clientID, productID
func (_m *IService) RemoveProduct(ctx context.Context, clientID uuid.UUID, productID uuid.UUID) error {
	ret := _m.Called(ctx, clientID, productID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, clientID, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewIService interface {
	mock.TestingT
	Cleanup(func())
}

// NewIService creates a new instance of IService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewIService(t mockConstructorTestingTNewIService) *IService {
	mock := &IService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
