basePath: /
definitions:
  controller.AddProductPayload:
    properties:
      client_id:
        format: uuid
        type: string
      comments:
        type: string
      product_id:
        format: uuid
        type: string
      quantity:
        example: 1
        minimum: 1
        type: integer
    required:
    - client_id
    - product_id
    - quantity
    type: object
  controller.EditProductPayload:
    properties:
      client_id:
        format: uuid
        type: string
      comments:
        type: string
      product_id:
        format: uuid
        type: string
      quantity:
        example: 2
        type: integer
    required:
    - client_id
    - product_id
    - quantity
    type: object
  controller.GetCartPayload:
    properties:
      client_id:
        format: uuid
        type: string
    required:
    - client_id
    type: object
  controller.RemoveProductPayload:
    properties:
      client_id:
        format: uuid
        type: string
      product_id:
        format: uuid
        type: string
    required:
    - client_id
    - product_id
    type: object
  product.Product:
    properties:
      category:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: string
      name:
        type: string
      price:
        type: number
    type: object
host: localhost:8080
info:
  contact: {}
  description: Fast Food API for FIAP Tech course
  title: Tech Challenge Food API
  version: 0.1.0
paths:
  /cart/add-product:
    post:
      consumes:
      - application/json
      description: Adds a Product to Customer's Cart
      parameters:
      - description: AddProductPayload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/controller.AddProductPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: '{\"error\": \"Internal Server Error\"}'
          schema:
            additionalProperties: true
            type: object
      tags:
      - Cart
  /cart/edit-product:
    post:
      consumes:
      - application/json
      description: Edits a Product from Customer's Cart
      parameters:
      - description: EditProductPayload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/controller.EditProductPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: '{\"error\": \"Internal Server Error\"}'
          schema:
            additionalProperties: true
            type: object
      tags:
      - Cart
  /cart/overview:
    post:
      consumes:
      - application/json
      parameters:
      - description: GetCartPayload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/controller.GetCartPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      tags:
      - Cart
  /cart/remove-product:
    post:
      consumes:
      - application/json
      description: Removes a Product from Customer's Cart
      parameters:
      - description: RemoveProductPayload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/controller.RemoveProductPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "500":
          description: Internal Server Error
      tags:
      - Cart
  /product:
    get:
      consumes:
      - application/json
      parameters:
      - description: Name of Product
        in: path
        name: search
        type: string
      - description: Category of Product
        in: path
        name: category
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: product.Product
          schema:
            $ref: '#/definitions/product.Product'
        "500":
          description: '{\"error\": \"something went bad :(\"}'
          schema:
            additionalProperties: true
            type: object
      summary: Search products with given criteria
      tags:
      - Product
  /product/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: ID of Product
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "500":
          description: '{\"error\": \"something went bad :(\"}'
          schema:
            additionalProperties: true
            type: object
      summary: Delete a Product with given ID
      tags:
      - Product
swagger: "2.0"
